// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'label': string;
  'labelWrap': string;
  'pokemonAbilities': string;
  'pokemonAbilitiesText': string;
  'pokemonCard': string;
  'pokemonCircle': string;
  'pokemonDefAndAttack': string;
  'pokemonDefAndAttackItem': string;
  'pokemonExp': string;
  'pokemonGenAndCircle': string;
  'pokemonGeneration': string;
  'pokemonHealth': string;
  'pokemonHealthAndExp': string;
  'pokemonImage': string;
  'pokemonInfo': string;
  'pokemonName': string;
  'pokemonNums': string;
  'pokemonPic': string;
  'pokemonProgressBar': string;
  'pokemonProgressBarReady': string;
  'pokemonState': string;
  'pokemonStateText': string;
  'pokemonStats': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
